const placesData = [
  {
    id: 1,
    name: "Machu Picchu",
    location: "Peru",
    category: "Historical",
    description: "Machu Picchu is an ancient Incan citadel set high in the Andes Mountains in Peru, renowned for its dry-stone walls and panoramic views.",
    imageUrl: "/places/machu-picchu.jpg",
  },
  {
    id: 3,
    name: "Chichen Itza",
    location: "Mexico",
    category: "Historical",
    description: "Chichen Itza is a large pre-Columbian archaeological site in Mexico, featuring a pyramid and ancient ruins.",
    imageUrl: "/places/chichen-itza.jpg",
  },
  {
    id: 2,
    name: "Great Barrier Reef",
    location: "Australia",
    category: "Natural",
    description: "The Great Barrier Reef is the world's largest coral reef system, composed of over 2,900 individual reefs and 900 islands stretching over 2,300 kilometers.",
    imageUrl: "/places/great-barrier-reef.jpg",
  },
  {
    id: 4,
    name: "The Amazon Rainforest",
    location: "Brazil/Various",
    category: "Natural",
    description: "The Amazon Rainforest is the largest rainforest on Earth, home to a staggering diversity of wildlife, plants, and indigenous communities.",
    imageUrl: "/places/the-amazon-rainforest.jpg",
  },
  {
    id: 5,
    name: "Grand Canyon",
    location: "USA",
    category: "Natural",
    description: "The Grand Canyon is a massive canyon in Arizona, carved by the Colorado River, known for its stunning rock formations and breathtaking views.",
    imageUrl: "/places/grand-canyon.jpg",
  },
  {
    id: 6,
    name: "Pyramids of Giza",
    location: "Egypt",
    category: "Historical",
    description: "The Pyramids of Giza are iconic structures in Egypt, built as tombs for the pharaohs and guarded by the Sphinx.",
    imageUrl: "/places/pyramids-of-giza.jpg",
  },
  {
    id: 7,
    name: "Venice",
    location: "Italy",
    category: "Cultural",
    description: "Venice is a unique city built on a network of canals, known for its historic architecture, art, and romantic atmosphere.",
    imageUrl: "/places/venice.jpg",
  },
  {
    id: 8,
    name: "Banff National Park",
    location: "Canada",
    category: "Natural",
    description: "Banff National Park is a stunning Canadian park with glaciers, mountains, and turquoise lakes, offering breathtaking landscapes.",
    imageUrl: "/places/banff-national-park.jpg",
  },
  {
    id: 9,
    name: "Tokyo",
    location: "Japan",
    category: "Modern",
    description: "Tokyo is a vibrant and futuristic city, blending traditional culture with modern technology, and known for its lively neighborhoods.",
    imageUrl: "/places/tokyo.jpg",
  },
  {
    id: 10,
    name: "St. Petersburg",
    location: "Russia",
    category: "Cultural",
    description: "St. Petersburg is a cultural hub in Russia, known for its historic architecture, art museums, and the iconic Hermitage.",
    imageUrl: "/places/st-petersburg.jpg",
  },
  {
    id: 11,
    name: "The Colosseum",
    location: "Italy",
    category: "Historical",
    description: "The Colosseum is an ancient Roman amphitheater known for its gladiator contests and grand architectural design.",
    imageUrl: "/places/the-colosseum.jpg",
  },
  {
    id: 12,
    name: "Petra",
    location: "Jordan",
    category: "Historical",
    description: "Petra is a famous archaeological site in Jordan, featuring rock-cut architecture and water conduit system.",
    imageUrl: "/places/petra.jpg",
  },
  {
    id: 13,
    name: "Iguazu Falls",
    location: "Argentina/Brazil",
    category: "Natural",
    description: "Iguazu Falls is a stunning waterfall system on the border of Argentina and Brazil, surrounded by lush rainforest.",
    imageUrl: "/places/iguazu-falls.jpg",
  },
  {
    id: 14,
    name: "Angkor Wat",
    location: "Cambodia",
    category: "Historical",
    description: "Angkor Wat is a massive temple complex in Cambodia, known for its intricate architecture and religious significance.",
    imageUrl: "/places/angkor-wat.jpg",
  },
  {
    id: 15,
    name: "The Louvre",
    location: "France",
    category: "Cultural",
    description: "The Louvre is the world's largest art museum and a historic monument in Paris, housing a vast collection of art and artifacts.",
    imageUrl: "/places/the-louvre.jpg",
  },
  {
    id: 16,
    name: "Galápagos Islands",
    location: "Ecuador",
    category: "Natural",
    description: "The Galápagos Islands are a unique archipelago known for their diverse wildlife, including giant tortoises and marine iguanas.",
    imageUrl: "/places/galapagos-islands.jpg",
  },
  {
    id: 17,
    name: "Marrakech",
    location: "Morocco",
    category: "Cultural",
    description: "Marrakech is a vibrant city in Morocco, known for its bustling markets, historic palaces, and vibrant street life.",
    imageUrl: "/places/marrakech.jpg",
  },
  {
    id: 18,
    name: "Fiordland National Park",
    location: "New Zealand",
    category: "Natural",
    description: "Fiordland National Park is a scenic wonderland in New Zealand, featuring fiords, waterfalls, and snow-capped mountains.",
    imageUrl: "/places/fiordland-national-park.jpg",
  },
  {
    id: 19,
    name: "Dubrovnik",
    location: "Croatia",
    category: "Historical",
    description: "Dubrovnik is a historic coastal city in Croatia, known for its well-preserved medieval architecture and city walls.",
    imageUrl: "/places/dubrovnik.jpg",
  },
  {
    id: 20,
    name: "Antelope Canyon",
    location: "USA",
    category: "Natural",
    description: "Antelope Canyon is a slot canyon in Arizona, famous for its stunning sandstone formations and vibrant light beams.",
    imageUrl: "/places/antelope-canyon.jpg",
  },
  {
    id: 21,
    name: "Dubai",
    location: "United Arab Emirates",
    category: "Modern",
    description: "Dubai is a futuristic city known for its iconic skyscrapers, luxury shopping, and innovative architecture.",
    imageUrl: "/places/dubai.jpg",
  },
  {
    id: 22,
    name: "Aletsch Glacier",
    location: "Switzerland",
    category: "Natural",
    description: "Aletsch Glacier is the largest glacier in the Alps, offering breathtaking views of icy landscapes and surrounding peaks.",
    imageUrl: "/places/aletsch-glacier.jpg",
  },
  {
    id: 23,
    name: "Easter Island",
    location: "Chile",
    category: "Historical",
    description: "Easter Island is known for its monumental statues called Moai, created by the Rapa Nui people, and its remote location in the Pacific Ocean.",
    imageUrl: "/places/easter-island.jpg",
  },
  {
    id: 24,
    name: "The Amazon Rainforest",
    location: "Brazil/Various",
    category: "Natural",
    description: "The Amazon Rainforest is the largest rainforest on Earth, home to a staggering diversity of wildlife, plants, and indigenous communities.",
    imageUrl: "/places/the-amazon-rainforest.jpg",
  },
  {
    id: 25,
    name: "Acropolis of Athens",
    location: "Greece",
    category: "Historical",
    description: "The Acropolis of Athens is an ancient citadel on a rocky outcrop, featuring the Parthenon and other historic structures from ancient Greece.",
    imageUrl: "/places/acropolis-of-athens.jpg",
  },
  {
    id: 26,
    name: "The Great Wall of China",
    location: "China",
    category: "Historical",
    description: "The Great Wall of China is an ancient fortification, stretching across northern China, and a UNESCO World Heritage site.",
    imageUrl: "/places/the-great-wall-of-china.jpg",
  },
  {
    id: 27,
    name: "Amsterdam",
    location: "Netherlands",
    category: "Cultural",
    description: "Amsterdam is a charming city known for its picturesque canals, historic architecture, and vibrant cultural scene.",
    imageUrl: "/places/amsterdam.jpg",
  },
  {
    id: 28,
    name: "Plitvice Lakes National Park",
    location: "Croatia",
    category: "Natural",
    description: "Plitvice Lakes National Park is a breathtaking natural wonder with cascading lakes, waterfalls, and lush greenery.",
    imageUrl: "/places/plitvice-lakes-national-park.jpg",
  },
];

export default placesData;